name: Build RediSearch with COORD: oss on Ubuntu 22.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        coord: [oss]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build RediSearch
      run: |
        mkdir -p build
        cd build
        cmake -D COORD=${{ matrix.coord }} ..
        make

    - name: Run tests
      run: |
        cd build
        ctest

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rediseearch-build
        path: build/
